### ISSUE TITLE
Broken link to Northwind from readme.md

### ISSUE THREAD

**Issue by hugosenari** [ebran/grim#30]
Hi,

Readme link is: ./tutorials/Northwind.nim  (404)
It should link to: ./tutorials/northwind.nim (200)

Maybe in this context, would be better it point to .md (not .nim)

:-)

**Comment by ebran** [comment]
Hi, good to see that the library is being used! Who figured... Fixed!

Wrote this library in the winter/spring during commute to work, but then covid hit and there was no more commuting. :confused:
